In [7]:
import numpy as np
from sklearn import preprocessing as _

In [36]:
input_data = np.random.randint(-5,5,size = (3,4))
print(input_data)

[[ 3 -3 -1  1]
 [ 4 -5 -1 -5]
 [-2 -4 -5  0]]


Some of the important preprocessing that are most useful are as follows:
- Binarization
- Mean Removal
- Scaling
- Normalization

In [22]:
#Binarization
preprocessing.binarize(input_data,threshold=3)

array([[0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0]])

In [45]:
#Mean Removal
print(preprocessing.scale(input_data))

[[ 0.50800051  1.22474487  0.70710678  0.88900089]
 [ 0.88900089 -1.22474487  0.70710678 -1.3970014 ]
 [-1.3970014   0.         -1.41421356  0.50800051]]


c:\python36_v5\envs\py3.6.5\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)


In [46]:
#_scaler = preprocessing.MinMaxScaler()
print(preprocessing.minmax_scale(input_data,feature_range=(1,3)))

[[2.66666667 3.         3.         3.        ]
 [3.         1.         3.         1.        ]
 [1.         2.         1.         2.66666667]]


c:\python36_v5\envs\py3.6.5\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64.
  warnings.warn(msg, DataConversionWarning)


In [44]:
scalar_ = preprocessing.MinMaxScaler(feature_range=(1,3))
scalar_.fit_transform(input_data)

c:\python36_v5\envs\py3.6.5\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[2.66666667, 3.        , 3.        , 3.        ],
       [3.        , 1.        , 3.        , 1.        ],
       [1.        , 2.        , 1.        , 2.66666667]])

In [48]:
data_normalized_l1 = preprocessing.normalize(input_data, norm='l1') 
print(data_normalized_l1)

[[ 0.375      -0.375      -0.125       0.125     ]
 [ 0.26666667 -0.33333333 -0.06666667 -0.33333333]
 [-0.18181818 -0.36363636 -0.45454545  0.        ]]


In [49]:
data_normalized_l2 = preprocessing.normalize(input_data, norm='l2') 
print(data_normalized_l2)

[[ 0.67082039 -0.67082039 -0.2236068   0.2236068 ]
 [ 0.48867778 -0.61084722 -0.12216944 -0.61084722]
 [-0.2981424  -0.59628479 -0.74535599  0.        ]]


In [56]:
input_labels = ['red', 'black', 'red', 'green', 'black', 'yellow', 'white'] 

In [57]:
encoder = preprocessing.LabelEncoder().fit(input_labels)

In [61]:
print(encoder.classes_)
print(encoder.transform(['red']))

['black' 'green' 'red' 'white' 'yellow']
[2]


array(['black', 'green', 'red', 'white', 'yellow'], dtype='<U6')